// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocietyMS.Data;

#nullable disable

namespace SocietyMS.Migrations
{
    [DbContext(typeof(Dbcontext))]
    [Migration("20251119075426_ikjkjk")]
    partial class ikjkjk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocietyMS.Models.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("SocietyMS.Models.Charges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("SocietyMS.Models.Dues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("membershipId")
                        .HasColumnType("int");

                    b.Property<int>("membershipinfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("membershipinfoId");

                    b.ToTable("Dues");
                });

            modelBuilder.Entity("SocietyMS.Models.Membershipinfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Charges")
                        .HasColumnType("int");

                    b.Property<int>("Personal_Id")
                        .HasColumnType("int");

                    b.Property<int>("Personalinfomember_id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Personalinfomember_id");

                    b.ToTable("Membershipinfos");
                });

            modelBuilder.Entity("SocietyMS.Models.Personalinfo", b =>
                {
                    b.Property<int>("member_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("member_id"));

                    b.Property<int>("CnicNo")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kin_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kin_Relation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kin_adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kin_cnic")
                        .HasColumnType("int");

                    b.Property<string>("membercast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permanentadress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phoneno")
                        .HasColumnType("int");

                    b.Property<string>("postaladress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("religion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("member_id");

                    b.ToTable("Personalinfos");
                });

            modelBuilder.Entity("SocietyMS.Models.Plot", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Plots");
                });

            modelBuilder.Entity("SocietyMS.Models.Trsfrmembership", b =>
                {
                    b.Property<int>("transfer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transfer_Id"));

                    b.Property<int>("Date")
                        .HasColumnType("int");

                    b.Property<int>("new_member_id")
                        .HasColumnType("int");

                    b.Property<int>("past_member_id")
                        .HasColumnType("int");

                    b.HasKey("transfer_Id");

                    b.ToTable("Trsfrmemberships");
                });

            modelBuilder.Entity("SocietyMS.Models.Dues", b =>
                {
                    b.HasOne("SocietyMS.Models.Membershipinfo", "membershipinfo")
                        .WithMany()
                        .HasForeignKey("membershipinfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("membershipinfo");
                });

            modelBuilder.Entity("SocietyMS.Models.Membershipinfo", b =>
                {
                    b.HasOne("SocietyMS.Models.Personalinfo", "Personalinfo")
                        .WithMany()
                        .HasForeignKey("Personalinfomember_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personalinfo");
                });
#pragma warning restore 612, 618
        }
    }
}
